### ISSUE TITLE
NullPointerException in generated NodeListener

### ISSUE THREAD

**Issue by sogern** [enggei/nextgen#13]
**Exception during parsing (sparql/Tests.java):**

`java.lang.NullPointerException
	at com.generator.generators.sparql.parser.SparqlNodeListener.enterPrologue(SparqlNodeListener.java:1007)
	at com.generator.generators.sparql.parser.SparqlParser$PrologueContext.enterRule(SparqlParser.java:251)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at com.generator.util.AntlrTestUtil.testParserRule(AntlrTestUtil.java:104)
	at com.generator.util.AntlrTestUtil.testParserRule(AntlrTestUtil.java:99)
`

**Suggested action:**

Change generated output for *NodeListener from
`onEnter(new Node("Prologue", arg.getText(), arg.getStart().getText(), arg.getStop().getText()));`
to
`onEnter(new Node("Prologue", arg.getText(), arg.getStart().getText(), arg.getStop() != null ? arg.getStop().getText() : null));`

**Comment by enggei** [comment]
nullpointer fixed with suggested action, using "" instead of null
